name: Kotlin
on: [push,pull_request]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: build and test
        run: ./gradlew build test --continue --info
