name: Kotlin
on: [push,pull_request]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: build and test
        run: ./gradlew build test --continue --info
