name: Kotlin
on: [push,pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin" 
          java-version: '11'

      - name: Archive test result
        uses: actions/upload-artifact@v2
        with:
          name: build_test_report
          path: /build/reports/tests/
